### PR TITLE
Update keyboard access

### PR DESCRIPTION
**Pull request by paclough**
Enable keyboard to focus hidden player controls

Add outline conditionally using a class

Update Gemfile

Update Gemfile.lock

Turn off outline for .avalon-player

### CODE REVIEW

**Comment by cjcolvar** [comment]
I'm a little concerned with the amount of changes to the Gemfile.lock at this point in the release process.  Is it possible to constrain the number of dependency version changes to just those needed for this PR?

**Comment by paclough** [comment]
I submitted pull requests for the other avalon projects (mediaelement-rails, mediaelement-quality-selector and mediaelement-skin-avalon). I think if I re-point to master for those gems we could minimize the changes to Gemfile/Gemfile.lock, since the only other change was pinning bootstrap-sass.

**Comment by bkeese** [comment]
The PRs for the other projects have been merged, can you unpin them in this gemfile?

**Comment by paclough** [comment]
Yep - working on it now

**Pull request merged**
