### PR TITLE
From IU customization

### PR DESCRIPTION
**Pull request by Dananji**
Following is a list of commits that were omitted in this PR;

1. Set timeliner to full width
2. Fix VOV-6089: Unnecessary scrollbar in smaller window (this horizontal scrollbar was introduced by the IU header and footer customization)
3. VOV-6092: tighten up collection cards
4. Make field buttons on resource description be gray
5. Show full unit name in AZSort view when no description available
6. Upgrage axios to deal with false XSS warning bug
7. Use new persona-aware method for creating a new user
8. Show physical format facet
9. Use 4 columns instead of 3 in Collections

### CODE REVIEW

**Comment by Dananji** [comment]
@cjcolvar The codeclimate issues, I don't understand the code there to know how to fix those. Can you please check them out when you have time? Thanks!

**Comment by joncameron** [comment]
I would like these to be added to core from the list of currently omitted:

# 1 Set timeliner to full width
# 3 VOV-6092: tighten up collection cards
# 4 Make field buttons on resource description be gray
# 5 Show full unit name in AZSort view when no description available
# 6  Upgrage axios to deal with false XSS warning bug
# 9 Use 4 columns instead of 3 in Collections

**Comment by cjcolvar** [comment]
@Dananji I can work with you to fix those two code climate issues.  One of them looks like a bug so I'm glad it caught it.

**Comment by Dananji** [comment]
@cjcolvar I will pick the commits the Jon mentioned in the comment.

**Comment by Dananji** [comment]
For the, `6 Upgrage axios to deal with false XSS warning bug`; axios was already updated in core so there was nothing to commit there.

**Pull request merged**
