### PR TITLE
Add document action for adding to playlist

### PR DESCRIPTION
**Pull request by bkeese**

### CODE REVIEW

**Comment by cjcolvar** [comment]
Can you add a test for #add_to_playlist_action?

**Comment by cjcolvar** [comment]
@joncameron @davidschober Can you two review this and give approval (or not)?  This adds the ability to add a whole item (each section as a separate playlist item) to a playlist from the manage selected items tab.

**Comment by bkeese** [comment]
Here's what it looks like:
image

**Comment by davidschober** [comment]
Just to verify workflow:

* Select items
* Click “manage selected”
* Click "Add to Playlist”
* See attached screenshot and pick your playlist. 

I’m good with this.

**Comment by joncameron** [comment]
Looks good to me as well. Moving to done.

**Pull request merged**
