### PR TITLE
update copyright

### PR DESCRIPTION
**Pull request by bkeese**
Update copyright dates for 2018

### CODE REVIEW

**Comment by bkeese** [comment]
What license updater tool? I just updated files that had copyright statements already.

**Comment by cjcolvar** [comment]
@bkeese https://wiki.dlib.indiana.edu/display/VarVideo/Update+License+Headers

**Comment by bkeese** [comment]
Can we merge this one? Then I can use the tool against what's left.

**Comment by bkeese** [comment]
That license_header gem isn't working for me. Probably a windows/unix thing. Also, it needs to be updated for ES6, which I think is where most of our new files are. I'll manually add the license headers to those.

**Pull request merged**
