### PR TITLE
Configure eslint using hyrax's configuration

### LINKED ISSUE #2445: Configure gem eslint-rails for JavaScript linting of MEJS4 files
### Description
Add & configure `eslint-rails` gem to lint our MEJS4 javascript moving forward.   I tried adding and configuring the gem, but it didn't work as expected following the Github documentation.  Need to spend more time with it.

This is important to get ahead of Code Climate warnings prior to pull requests.

### Tasks
- [ ] add `eslint-rails` gem to application in the right place.
- [ ] Configure the linting rules for our application

### PR DESCRIPTION
**Pull request by cjcolvar**
Resolves #2445 

I added instructions to the `README.md` so we won't forget how to setup and run it.

### CODE REVIEW

**Comment by adamjarling** [comment]
How should we handle the codeclimate errors?   Want me to pull this branch down, fix (the quick ones) and re-push?

**Comment by cjcolvar** [comment]
Sure, you could do that.  If any are too gnarly, you could skip them with an inline comment: https://eslint.org/docs/user-guide/configuring.html#configuring-rules

**Comment by adamjarling** [comment]
@cjcolvar Verified all works as expected running local eslint on project files.

**Comment by cjcolvar** [comment]
:+1: Nice

**Pull request merged**
