### PR TITLE
Add mejs4 icon svg backgrounds

### PR DESCRIPTION
**Pull request by lealeelu**

### CODE REVIEW

**Comment by lealeelu** [comment]
I rebased on develop, I don't understand why that extra code is there.

**Comment by lealeelu** [comment]
Ok, redid the commit without those extra changes. Problem now is that I'm getting this error when trying to watch a video from the video's page. Playlist playing works fine for some reason. 
image
It seems unrelated to what I was doing.

**Comment by bkeese** [comment]
@adamjarling: I think this is a bug in the MEJS4 segment PR. Happens when there is a mediaobject with only one masterfile and no structure, right? In that case, there is no accordian for the new js to reference.

**Comment by adamjarling** [comment]
@bkeese Ah, I'll pull it down and look at that scenario.  Sorry about that.

**Pull request merged**
