### PR TITLE
Make upload button clickable not just text

### PR DESCRIPTION
**Pull request by lealeelu**
If you click the upload button and not the upload text, nothing will happen. I made it so that the whole button works.

### CODE REVIEW

**Comment by lealeelu** [comment]
@bkeese It doesn't but I know what you're talking about. I can fix that up too.

**Comment by carrickr** [comment]
@lealeelu Are you planning to update this PR to fix that?

**Comment by lealeelu** [comment]
Yup, I'll update this PR @carrickr

**Comment by lealeelu** [comment]
@bkeese @carrickr ok, Added white text fix. I think I'm done with this one unless you find something else.

**Comment by bkeese** [comment]
As long as you thoroughly tested the upload button after making this change. There was some reason we put that z-index in there.  I think there were cases where the button wasn't clickable. Maybe certain browsers? I can't remember for sure.

**Comment by lealeelu** [comment]
I found this commit you did three years ago that added it.
https://github.com/avalonmediasystem/avalon/commit/82b1e100d954533234aa40a4c7022b5280ab0a50

Do you know why we would want it at the same level as the modal?

**Comment by bkeese** [comment]
I think I chose that because it was an available variable that would put an element over the page. There were no modals on that page at the time. Then browse everything and later that "loading" dialog came along and screwed things up. Anyway, the point was to keep the upload button at the top and thus clickable.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by cjcolvar** [comment]
Is this ready to go?  Is there anything else that needs to be done?

**Comment by bkeese** [comment]
I am afraid that completely removing that z-index will re-break the upload button.

**Comment by lealeelu** [comment]
I want to get more testing done on something other than chrome.

**Comment by cjcolvar** [comment]
@lealeelu browserstack could be helpful for this.

**Comment by joncameron** [comment]
@lealeelu Definitely, you should feel free to use our main BrowserStack account: https://wiki.dlib.indiana.edu/display/VarVideo/BrowserStack

**Comment by lealeelu** [comment]
Checked it in safari, android, edge and chrome. I wasn't able to break it so I think this pull request is good to go.

**Pull request merged**
