### PR TITLE
Rough draft of collection index and landing page

### PR DESCRIPTION
**Pull request by cjcolvar**
This PR adds routes and controller actions for the end-user focused collection index and view pages.  Gated discovery is applied through media objects: if you can discover at least one item in a collection then you can see the collection.  Conversely though if you can't discover at least one item in a collection then it doesn't show up in the index nor are you allowed to see the landing page.  Alternatively (or in addition) we could give collections themselves visibility and special exceptions which would explicitly allow the ability to discover/read a collection.

### CODE REVIEW

**Comment by Dananji** [comment]
@cjcolvar When I click on `Collections` tab, I get this error;

collection_index_error

Is there anything I need to do?

**Comment by cjcolvar** [comment]
@Dananji Try restarting your avalon docker container and see if that fixes it.

**Comment by Dananji** [comment]
Thanks @cjcolvar ! It worked.
Then this happened;

nil_error

When there is at least one collection without a description, this error occurs.

And when there are descriptions for all collections, it looks as follows;

collection_index

**Comment by cjcolvar** [comment]
Good catch.  I'll take care of that now.

**Pull request merged**
