### PR TITLE
Use start canvas and time props in Ramp for sections and custom start times

### PR DESCRIPTION
**Pull request by Dananji**
This PR includes a new build of Ramp, which has work related to the following issues;
- https://github.com/samvera-labs/ramp/issues/316
- https://github.com/samvera-labs/ramp/issues/289
- https://github.com/samvera-labs/ramp/issues/310
- https://github.com/samvera-labs/ramp/issues/252
- https://github.com/avalonmediasystem/avalon/issues/5504

And a couple of changes to JavaScript to fix some of the console errors on the item view page for share and create timeline actions.

### CODE REVIEW

**Review by masaball — APPROVED** [review]
Looks good!

**Comment by Dananji** [comment]
Right! How does the user gets to that URL in UI? It seems they are both similar use-cases, so I don't mind including that work in this PR.

**Comment by masaball** [comment]
In 7.6, the `?position=` query is added to the URL when a user selects an item from the "Playlist Items" sidebar on the playlist view page. So the full url becomes "https://example.com/playlists/1?position=1".

Since the items sidebar just triggers canvas switches in the manifest, I don't think the URL is generated by UI actions in 7.7 currently.

**Comment by Dananji** [comment]
I was looking at the previous playlist page in MCO, and we have the `?position=` URL in the playlist item link. But in the new UI its the Canvas URL. So it seems to me there's some things we need to discuss and refine on this implementation. And there's a ticket in the backlog related to this https://github.com/avalonmediasystem/avalon/issues/5514. 
I guess the playlist work could be part of that ticket?

**Comment by masaball** [comment]
Yeah, saving the playlist work for #5514 sounds good. Had missed that in the backlog.

So I think we're good to go with this PR.

**Pull request merged**
