### PR TITLE
3755 collections page tighten up

### PR DESCRIPTION
**Pull request by adamjarling**
This addresses the issues detailed in #3755 Except for the "Turn off field drop-down autocomplete on search field".  Where is this happening?  Can you attach a screen shot?

### CODE REVIEW

**Comment by adamjarling** [comment]
I'm going to push up a few more tweaks I just noticed...  If anyone's close to merging, please hold off a few...

**Comment by adamjarling** [comment]
Ok, re-pushed and good to go.

**Comment by adamjarling** [comment]
Hey @cjcolvar Any ideas on this failing test?  Looks like something to do with Playlists?

```
Failed examples:

rspec ./spec/controllers/playlists_controller_spec.rb:333 # PlaylistsController PUT #update_multiple delete deletes a playlist item
```

**Comment by cjcolvar** [comment]
@adamjarling It looks like a circleci hiccup:
```
 Faraday::ConnectionFailed:
       execution expired
```
I'd just ignore it at this point instead of rerunning the build since we've got a number of PRs waiting on circleci.
I'm hoping to merge #3759 before anything else since it should help with restarting background jobs after automatic deployment on merge.

**Comment by adamjarling** [comment]
@cjcolvar Ok, I'll let you merge it in whenever you want.

**Pull request merged**
