### PR TITLE
Upgrade omniauth to 2.0.0 for CSRF fix

### PR DESCRIPTION
**Pull request by phuongdh**
Replaces https://github.com/avalonmediasystem/avalon/pull/4367

### CODE REVIEW

**Review by Dananji — APPROVED** [review]
@phuongdh The changes in the `Gemfile.lock` in this PR are different from the changes in the original PR. But I see that the `omniauth` changes are in here. So I think this is good :+1:

**Comment by phuongdh** [comment]
> @phuongdh The changes in the `Gemfile.lock` in this PR are different from the changes in the original PR. But I see that the `omniauth` changes are in here. So I think this is good

Good catch. I actually missed the omniauth version bump. 2.x introduced some [breaking change](https://github.com/omniauth/omniauth/releases/tag/v2.0.0) so this will need to be tested well.

**Review by Dananji — APPROVED** [review]
:+1:

**Comment by phuongdh** [comment]
New devise is breaking one of our routes. Needs more investigation.
```
     Failure/Error: visit "/users/auth/identity"
     
     Capybara::InfiniteRedirectError:
       redirected more than 5 times, check for infinite redirects.
```

**Comment by phuongdh** [comment]
Wait till devise release their fix which is only in master branch for now. https://github.com/heartcombo/devise/issues/5354#issuecomment-791386243

**Comment by joncameron** [comment]
Closing in favor of #4574

**Pull request closed without merging**
