### PR TITLE
Configure qulity plugin button title

### LINKED ISSUE #2508: add quality control tooltip
## Description

Ensure the quality control tooltip exists on me4js.

## done

- you hover and the quality control tool tip pops 

#2504

### PR DESCRIPTION
**Pull request by bkeese**
Fixes #2508 

Adds text for quality button label.

### CODE REVIEW

**Comment by phuongdh** [comment]
Doesn't the plugin already have this text as default? Why do we need to set it one more time here?

**Comment by bkeese** [comment]
Without setting it here, the string 'mejs.quality-quality' is being used. Is there somewhere else to set it?

**Comment by phuongdh** [comment]
I forgot that we're using their plugin instead of ours! Anyway reading through their code, it seems to be a bug that I will submit a PR for.

**Comment by bkeese** [comment]
I wondered if it was related to the i118n templating stuff in mejs4 plugins.

**Comment by phuongdh** [comment]
Here is my PR in their repo https://github.com/mediaelement/mediaelement-plugins/pull/107

**Comment by cjcolvar** [comment]
We can undo this PR once the upstream change gets merged.

**Pull request merged**
