### PR TITLE
Replace MEJS4 resize handler to stop embed player from infinitely exp…

### PR DESCRIPTION
**Pull request by phuongdh**
…anding on mobile Safari

### CODE REVIEW

**Comment by bkeese** [comment]
Interesting approach!

**Comment by cjcolvar** [comment]
Neat.  I like how it is scoped to the embed player!
@phuongdh do you think it is guaranteed that this plugin will be built (and therefore override the event handler) before the resize globalBind happens?

**Comment by phuongdh** [comment]
Hmm yeah I thought it wouldn't matter but on second thought I'll deploy this branch to Spruce and test.

**Comment by cjcolvar** [comment]
I think it is safe because the plugins are built synchronously and that happens before the resize globalBind, but now I'm wondering if the MEJS code will override the plugin since it runs later.
buildfeatures: https://github.com/mediaelement/mediaelement/blob/master/src/js/player.js#L683
resize handling: https://github.com/mediaelement/mediaelement/blob/master/src/js/player.js#L923-L935

**Comment by phuongdh** [comment]
That's what I'm fiddling with now. Changing quality makes it grow again!

**Comment by phuongdh** [comment]
Giving up for now. Feel free to mess with the branch and redeploy to Spruce

**Pull request closed without merging**
