### PR TITLE
Mediaelement.js 4 player preview

### PR DESCRIPTION
**Pull request by cjcolvar**
This PR is @adamjarling 's starting work on the mediaelement.js 4 player and the ability to toggle over to it using a query param.  This allows us to keep the ME.js 2 player default while still developing the ME.js 4 player.  This is important if we want to do another 6.x release before the ME.js 4 player is ready to ship, but if we don't think that will be the case then we could skip some of the complexity here and make it only the ME.js 4 player.  The other alternative is keeping this work on a branch or maintaining multiple active branches for release both of which make testing hard.

@avalonmediasystem/product-owners I'd like to hear your opinions about release cycle before merging this.

### CODE REVIEW

**Comment by davidschober** [comment]
My optimistic side wants to say, let's just push hard for ME4. But if we've already made the swapping work, and considering we have a few more playlist improvements that we need to ship. I say we target ME4 as a 6.3 and ship the final playlist improvements as 6.2 quickly to keep end users happy. 

@joncameron does that work for you?

**Comment by mcwhitaker** [comment]
I added the milestone because the work happened during sprint 132.

**Comment by joncameron** [comment]
@davidschober That works for me. Let's move forward then with ME4 as 6.3 and playlist improvements as 6.2.  @cjcolvar

**Comment by cjcolvar** [comment]
Fixes #2174.

**Pull request merged**
