### PR TITLE
No invalid objs

### LINKED ISSUE #2045: Media Objects Can Be Saved Without Required Fields (Title & Date)
### Descriptive summary
Server: spruce.dlib.indiana.edu
Browser: Firefox 53
Operating System: macOS 10.11.6

### Issue
Media objects can be saved without a title or date, which are required fields—objects should not save if these are absent.

### Expected behavior
Save operations are not allowed if there is no value in the Title or Date fields of the Resource Description form.

### Actual behavior
jun-09-2017 10-36-47
The record saves and the Fedora 4 ID becomes the Title.

### Steps to reproduce the behavior
1. Login to spruce.
2. Go to the resource description for a record, delete the Title or Date fields, and click Save
3. Warnings appear to the user (bark but no bite)
4. Go to the Preview/Object View and see that the Title and Date values are set

### Related work
Originally reported in #2039

### PR DESCRIPTION
**Pull request by cjcolvar**
Please thoroughly review this before merging.
Fixes #2045.

### CODE REVIEW

**Comment by cjcolvar** [comment]
We could wait on merging this a little bit since it has the chance to break ingest badly.

**Comment by carrickr** [comment]
Tagged it WIP just to ensure it doesn't get merged until we want it, probably after Chris gets back

**Comment by cjcolvar** [comment]
After some testing I found a few UI oddities that need to be addressed:

1. If you create a valid media object by adding title/date issued and saving then try to save without a title you get a flash error message as expected BUT it hangs around for one request if you click away to a different step of the workflow even though the save never persisted.

1. If you advance to the resource description step then go back to manage files before saving the required fields, you can upload a file and it looks okay but the master file never gets associated with the media object and it doesn't appear on the manage files page.

**Comment by cjcolvar** [comment]
I've resolved the two issues I identified and this is ready to be reviewed.  We'll still want to do more regression testing after merging but I think it is ready to go.

**Pull request merged**
