### PR TITLE
Update docker-compose for AWS changes

### PR DESCRIPTION
**Pull request by bkeese**
Update docker config for AWS streaming config changes

### CODE REVIEW

**Comment by bkeese** [comment]
Docker encoding and streaming no longer worked because of changes introduced in the AWS PR. This PR makes it work again.

**Comment by phuongdh** [comment]
Beside these, I suspect there might be more broken configs that we haven't found yet.

**Comment by cjcolvar** [comment]
So it sounds like we need documentation changes to account for the key changes of these configs.

**Comment by bkeese** [comment]
I created an upgrade instructions page and put it there. https://wiki.dlib.indiana.edu/display/VarVideo/Upgrading+Avalon+6.2+to+Avalon+6.3

**Pull request merged**
