### PR TITLE
Update year in license header

### PR DESCRIPTION
**Pull request by lealeelu**
Used this method:
https://wiki.dlib.indiana.edu/display/VarVideo/Update+License+Headers

### CODE REVIEW

**Comment by cjcolvar** [comment]
I don't think we should add headers wholesale to config or db/migrate since some of those files are not ours.

**Comment by lealeelu** [comment]
Then should I remove all headers of our headers from config and db/migrate?

**Comment by cjcolvar** [comment]
@mbklein what are your thoughts?  Is it worth putting the copyright header on config files, initializers, and db migrations?  We already have some on migrations but none in config.

**Comment by lealeelu** [comment]
I removed the headers from the config files since they weren't there to begin with. With the db/migrate files it looks like only four of them didn't have it to begin with and I recognize a couple that are probably written by us.

**Comment by cjcolvar** [comment]
I think all of the migration scripts that are having license headers added shouldn't.  So only migrations with existing license headers should be updated and none added.

**Comment by lealeelu** [comment]
@cjcolvar sounds good to me.

**Comment by cjcolvar** [comment]
One last thing: could you remove the test directory?  We don't need it and it's not our code anyways so it shouldn't have headers.

**Comment by lealeelu** [comment]
Updated again. How's that?

**Comment by cjcolvar** [comment]
:+1: thanks for doing this tedious work!

**Pull request merged**
