### PR TITLE
Pull in Structural Metadata Editor

### PR DESCRIPTION
**Pull request by cjcolvar**
Child of #3223

### CODE REVIEW

**Comment by adamjarling** [comment]
Maybe this entry gets around the issue mentioned above?  

https://github.com/avalonmediasystem/avalon/blob/a1a0783b7213f7853547997b100e1e6f4ceeb9bf/package.json#L4

I'd prefer to keep `@babel/runtime` out of `react-structural-metadata-editor` if possible.

**Comment by cjcolvar** [comment]
I'll make that change.

**Comment by cjcolvar** [comment]
@adamjarling It looks like the dependency on `babel-runtime` is coming from the compilation: https://github.com/avalonmediasystem/react-structural-metadata-editor/blob/master/es/containers/WaveformContainer.js#L1

I was able to figure out the issue with yarn asking you to choose a version to install.  The issue is that `babel-runtime` and `@babel/runtime` are different things and that line above references `babel-runtime` which only has a 6.26.0 release and no formal 7.0.0 release.  I created a branch in the SME packaging repo with `babel-runtime` included and removed it from avalon and things render without error.

**Comment by adamjarling** [comment]
@cjcolvar Ok yea lets do whatever works to get this running in Avalon.  

My thinking was that I can pull  `https://github.com/avalonmediasystem/react-structural-metadata-editor/tree/v1.1.0-without-babel-runtime` into an application which is not Avalon and it works fine.  So it seemed `babel-runtime` or `@babel-runtime` (whichever version `webpacker` uses, and yea with v `7` the packages are now prefixed with the `@`...learned that this week too)  would be an Avalon environment dependency.

Let's do whatever works though for now, and as long as we can pull `react-structural-metadata-editor` into an independent application and it still runs and doesn't seem to impact anything, then I'm fine with it.

Let me know what existing branches work for you, let's maybe get those tightened up and delete whatever becomes stale (so I don't get confused:)

**Comment by adamjarling** [comment]
Just testing around here, and in Avalon if I blow out my node modules folder, then do a `yarn install` given this `package.json` file, it loads:

https://github.com/avalonmediasystem/avalon/blob/3223-pull-sme-into-avalon/package.json

Something tells me leaving that `babel-runtime` in the exportable module is going to cause some weird issue in the future.  As long as we're using `nwb` package...something could end up conflicting.

**Comment by cjcolvar** [comment]
Child of #3223.

**Comment by cjcolvar** [comment]
Replaced with #3316

**Pull request closed without merging**
