### PR TITLE
Make selected items page span the entire container

### PR DESCRIPTION
**Pull request by Dananji**
Before:

Screenshot from 2019-12-26 11-07-36
After:

Screenshot from 2019-12-26 11-06-55

### CODE REVIEW

**Comment by bkeese** [comment]
This seems like a very broad selector. Are you sure we want this change everywhere it will apply?

**Comment by Dananji** [comment]
In mobile screens the buttons/items will always left-align making the list of buttons/items span to multiple lines. When `margin-left: 2px`, it looks like this;
Screenshot from 2019-12-26 11-20-30

So having the margin on right instead of left will make it look aligned. And in larger screen this makes no difference, because everything is on the same line.

I think we want to make this change everywhere it applies. WDYT?

**Comment by bkeese** [comment]
It's the elimination of max-width on all #co tent that I'm concerned about. I don't remember why that was there specifically, but I'll bet there was a reason, maybe on some other page.

**Comment by Dananji** [comment]
Ohh.. okay. Yes it is used in other places (e.g. Timeliner page, Search results, Media player section) When I tested those scenarios, and found that `max-width: 870px;` is dominated either by other CSS classes or inline styling. Removing `max-width: 870px;`, I couldn't see it affecting the UI to change.

**Pull request merged**
