### PR TITLE
Create dropbox folder before loading dropbox UI #4491

### PR DESCRIPTION
**Pull request by apertome**
PR for creating dropbox folder for STAGING branch

### CODE REVIEW

**Comment by apertome** [comment]
To test this, you'll want to do the following.

Make sure that you are seeing the error this fixes first from the target branch of this PR (`staging`):
- Set up a local filesystem-backed  dropbox in your dev environment, if you don't already have one.  
- Create a new collection. A folder should get created inside the dropbox folder that is based on the collection name. 
- Now delete the new dropbox folder and try to load the dropbox in the GUI. It will give you an error in the logs and it won't open.

Stop all containers.

Switch to this branch, bring your containers back up, and test that it fixes the issue.
- Navigating to the collection you created previously and try to open the dropbox again. It should work this time.
- Validate that the dropbox folder got recreated correctly

**Comment by Dananji** [comment]
On `staging` branch the dropbox GUI doesn't list any of the dropbox directories, instead it shows the files inside the collection's dropbox directory like below;
dropbox files
avalon gui

When I deleted the dropbox directory an empty window showed up without giving any errors.

On `dropbox-missing-folder-staging` branch, following the steps I was not able to see the dropbox directory getting recreated when `Open Dropbox` button is clicked.
Again I'm not sure whether this is related a config difference.

**Comment by apertome** [comment]
You'll need a local filesystem dropbox set up to test this. Here's how I set mine up.

```docker-compose.yml
comment these lines out, like this:
      # - SETTINGS__DROPBOX__PATH=s3://masterfiles/dropbox/
      # - SETTINGS__DROPBOX__UPLOAD_URI=s3://masterfiles/dropbox/

Add these lines (fix the path for your instance)
      - SETTINGS__DROPBOX__PATH=/home/mj82/src/avalon/dropbox
      - SETTINGS__DROPBOX__UPLOAD_URI=sftp:///localhost/dropbox/


```

**Review by Dananji — APPROVED** [review]
Looks good :+1:

**Pull request merged**
