### PR TITLE
Upgrade omniauth to 2.0

### PR DESCRIPTION
**Pull request by cjcolvar**
Replaces #4377

### CODE REVIEW

**Comment by cjcolvar** [comment]
#4553 should go in first then this can be rebased on top of that.

**Comment by cjcolvar** [comment]
If omniauth-saml is included in the Gemfile in #4553 then this PR will probably need to upgrade it to 2.0 in order to allow omniauth 2.0.  Other omniauth plugin gems may need to be upgraded as well.

**Comment by cjcolvar** [comment]
Looks like we're still running into this issue: https://github.com/avalonmediasystem/avalon/pull/4377#issuecomment-776294168

**Review by Dananji — APPROVED** [review]
Looks good :+1:

**Pull request merged**
